#!/bin/bash
#SBATCH -p gpu
#SBATCH -G 1
#SBATCH --job-name=wnRef1116
#SBATCH --output=/scratch/users/kuaifang/jobs/wnRef1116.out
#SBATCH --error=/scratch/users/kuaifang/jobs/wnRef1116.err
#SBATCH --time=12:0:0
#SBATCH --mem=32000
#SBATCH --qos=normal
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kuaifang@stanford.edu
source /home/users/kuaifang/envs/pytorch/bin/activate
python /home/users/kuaifang/GitHUB/geolearn/app/waterNet/CONUS/trainRef-1116.py 