#!/bin/bash
#SBATCH -p gpu
#SBATCH -G 1
#SBATCH --job-name=wnQC
#SBATCH --output=/scratch/users/kuaifang/jobs/wnQC.out
#SBATCH --error=/scratch/users/kuaifang/jobs/wnQC.err
#SBATCH --time=12:0:0
#SBATCH --mem=32000
#SBATCH --qos=normal
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kuaifang@stanford.edu
source /home/users/kuaifang/envs/pytorch/bin/activate
python /home/users/kuaifang/GitHUB/geolearn/app/waterNet/shChem/trainQTC-00955.py 
