#!/bin/bash
#SBATCH -p gpu
#SBATCH -G 1
#SBATCH --job-name=QN90-wn3
#SBATCH --output=/scratch/users/kuaifang/jobs/QN90-wn3.out
#SBATCH --error=/scratch/users/kuaifang/jobs/QN90-wn3.err
#SBATCH --time=24:0:0
#SBATCH --mem=32000
#SBATCH --qos=normal
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kuaifang@stanford.edu
source /home/users/kuaifang/envs/pytorch/bin/activate
python /home/users/kuaifang/GitHUB/geolearn/app/waterNet/sherlock/trainN3-QN90.py 