#!/bin/bash
#SBATCH -p gpu
#SBATCH -G 1
#SBATCH --job-name=temp
#SBATCH --output=/scratch/users/kuaifang/jobs/temp.out
#SBATCH --error=/scratch/users/kuaifang/jobs/temp.err
#SBATCH --time=24:0:0
#SBATCH --mem=32000
#SBATCH --qos=normal
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kuaifang@stanford.edu
source /home/users/kuaifang/envs/pytorch/bin/activate
python /home/users/kuaifang/GitHUB/geolearn/app/wqFull/sherlock/test.py 