#!/bin/bash
#SBATCH -p gpu
#SBATCH -G 1
#SBATCH --job-name=wn0119all
#SBATCH --output=/scratch/users/kuaifang/jobs/wn0119all.out
#SBATCH --error=/scratch/users/kuaifang/jobs/wn0119all.err
#SBATCH --time=12:0:0
#SBATCH --mem=32000
#SBATCH --qos=normal
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kuaifang@stanford.edu
source /home/users/kuaifang/envs/pytorch/bin/activate
python /home/users/kuaifang/GitHUB/geolearn/app/waterNet/EMMA/trainWNEMall-0119.py 