#!/bin/bash
#SBATCH -p gpu
#SBATCH -G 1
#SBATCH --job-name=wfq2-00955-B15
#SBATCH --output=/scratch/users/kuaifang/jobs/wfq2-00955-B15.out
#SBATCH --error=/scratch/users/kuaifang/jobs/wfq2-00955-B15.err
#SBATCH --time=24:0:0
#SBATCH --mem=32000
#SBATCH --qos=normal
#SBATCH --partition=owners
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kuaifang@stanford.edu
source /home/users/kuaifang/envs/pytorch/bin/activate
python /home/users/kuaifang/GitHUB/geolearn/app/waterNet/fullModel/trainModel.py 