#!/bin/bash
#SBATCH -p gpu
#SBATCH -G 1
#SBATCH -C "GPU_SKU:V100_PCIE|GPU_SKU:V100S_PCIE|GPU_SKU:V100_SXM2"
#SBATCH --job-name=wfq-00955-B15
#SBATCH --output=/scratch/users/kuaifang/jobs/wfq-00955-B15.out
#SBATCH --error=/scratch/users/kuaifang/jobs/wfq-00955-B15.err
#SBATCH --time=24:0:0
#SBATCH --mem=32000
#SBATCH --qos=normal
#SBATCH --partition=owners
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kuaifang@stanford.edu
source /home/users/kuaifang/envs/pytorch/bin/activate
python /home/users/kuaifang/GitHUB/geolearn/app/waterNet/fullModel/trainModel.py 